version: "3.9"

services:
  database-test:
    container_name: postgres-test
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  hoverfly-test:
    container_name: hoverfly-test
    image: spectolabs/hoverfly:latest
    volumes:
      - "./hoverfly:/hoverfly_app:ro"
    command:
      - "-webserver"
      - "-response-body-files-path=/hoverfly_app/responses"
      - "-import=/hoverfly_app/simulations/recommend.simulation.json"
    ports:
      - "8501:8500"
      - "8889:8888"
